application: home-page
version: 1
runtime: python27
api_version: 1
threadsafe: true
runtime: php
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: /favicon.ico
  upload: favicon\.ico

- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /pdf
  static_dir: pdf

- url: /php
  static_dir: php

- url: /.*
  script: home_page.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest